trigger: none #this is not a CI, the pipeline will be triggered manually

variables:
- group: 'GitHub Release Variables'
- name: 'GH_TOKEN'
  value: "$(Github-azuresdkci-personalaccesstoken)"
 

jobs:
  - job: 'Publish_API_docs_for_the_fluent_management_java_SDK'
  
    steps:
      - task: Npm@1
        displayName: 'npm install at root'
        inputs:
          command: 'install'
          
      - script: 'chmod 775 eng/pipelines/scripts/repo'
        displayName: 'change exec permissions on repo script'
        
      - script: 'cp  eng/pipelines/utils/commit.js node_modules/gift/lib/commit.js'
        displayName: 'copy over fixed commit.js file'
        
      - script: 'git config --global user.email "azuresdkci@users.noreply.github.com";git config --global user.name "azuresdkci"'
        displayName: 'set git user name and email'
        
      - script: 'export GH_TOKEN=$(Github-azuresdkci-personalaccesstoken);gulp publish:ref-docs;'
        displayName: 'gulp publish:ref-docs at root after setting env var for GH_TOKEN'
          
      - script: 'export GH_TOKEN=$(Github-azuresdkci-personalaccesstoken);gulp publish:sdk;'
        displayName: 'gulp publish:sdk at root after setting env var for GH_TOKEN'

      - task: Npm@1
        displayName: 'npm install at azure/java/azure-sdk'
        inputs:
          workingDir: 'azure/java/azure-sdk'
          command: 'install'
          
      - script: 'cp  eng/pipelines/utils/commit.js azure/java/azure-sdk/node_modules/gift/lib/commit.js'
        displayName: 'copy over fixed commit.js file'
        
      - script: 'cd azure/java/azure-sdk;export GH_TOKEN=$(Github-azuresdkci-personalaccesstoken);gulp publish;'
        displayName: 'gulp publish at azure/java/azure-sdk after setting env var for GH_TOKEN'
          
      - task: PublishPipelineArtifact@0
        condition: succeededOrFailed()
        displayName: 'Publish reports artifact'
        inputs:
          artifactName: track1reports
          targetPath: $(Build.ArtifactStagingDirectory)/data

