trigger: none #this is not a CI, the pipeline will be triggered manually


jobs:
  - job: 'Publish_API_docs_for_the_fluent_management_java_SDK'
  
    steps:
      - task: Npm@1
        displayName: 'npm install at root'
        inputs:
          command: 'install'
          
      - script: 'chmod 775 eng/pipelines/scripts/repo'
        displayName: 'change exec[ permissions on repo script'
          
      - task: gulp@1
        displayName: 'gulp publish:ref-docs at root'
        inputs:
          targets: 'publish:ref-docs'
          
      - task: gulp@1
        displayName: 'gulp publish:sdk at root'
        inputs:
          targets: 'publish:sdk'
          
      - task: Npm@1
        displayName: 'npm install at azure/java/azure-sdk'
        inputs:
          workingDir: 'azure/java/azure-sdk'
          command: 'install'
          
      - task: gulp@1
        displayName: 'gulp publish:ref-docs at azure/java/azure-sdk'
        inputs:
          workingDirectory: 'azure/java/azure-sdk'
          targets: 'publish'

      - task: PublishPipelineArtifact@0
        condition: succeededOrFailed()
        displayName: 'Publish reports artifact'
        inputs:
          artifactName: track1reports
          targetPath: $(Build.ArtifactStagingDirectory)/data

